print('Hello World')
print('Beknazar')
print('Ali')
print('Renat')
print('Iskender')
print('Manas')
print('Zhaiyl')
print('Daulet')
print('Kanyshai')
print('Eliza')
print('Assat')
print('Zhibek')
print('Altynai')
